USE NAFISKP201
CREATE TABLE KARYAWAN(
NAMA VARCHAR(15),
PEKERJAAN VARCHAR(15),
GAJI INT,
MKERJA INT)
1.Buat tabel dengan nama Karyawan pada database anda dengan struktur dan data
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('SUNARDI','STAF AHLI','1500000','3')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('AHMAD ZAENUDIN','DIREKTUR','5000000','8')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('JOKO MARTADI','ADMINISTRASI','800000','2')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('SUKOTJO','KEAMANAN','500000','3')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('ANDI SANYOTO','PEMBUKUAN','1000000','4')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('SANTOSO','ADMINISTRASI','1200000','6')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('MARIYANTI','STAF AHLI','2000000','1')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('RATMANTO','KEAMANAN','750000','4')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('MAHENDRA','SALESMAN','1000000','6')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('PARMADI BUDI','ADMINISTRASI','2000000','7')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('INDAH MULYONO','SEKRETARIS','3000000','5')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('ARIS HARYANTO','STAF AHLI','1800000','3')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('SARAJAYA','SALESMAN','1200000','1')
INSERT INTO KARYAWAN (NAMA,PEKERJAAN,GAJI,MKERJA) VALUES ('GUNARSO HALIM','STAF AHLI','1500000','1')

SELECT * FROM KARYAWAN

2. Tampilkan yang namanya di awali dengan huruf depan S
SELECT * FROM KARYAWAN WHERE NAMA LIKE 'S%'
3. Tampilkan yang pekerjaannya STAF AHLI
SELECT * FROM KARYAWAN WHERE PEKERJAAN LIKE 'STAF AHLI'
4. Tampilkan yang gajinya dibawah 1000000
SELECT * FROM KARYAWAN WHERE GAJI<1000000 
5. Tampilkan yang gajinya diatas 3000000
SELECT * FROM KARYAWAN WHERE GAJI>3000000 
6. Tampilkan gajinya antara 2000000 - 4000000
SELECT * FROM KARYAWAN WHERE GAJI>=2000000 AND GAJI<=4000000
7. Tampilkan data yang pekerjaannya ADMINISTRASI atau STAF AHLI
SELECT * FROM KARYAWAN WHERE PEKERJAAN LIKE 'ADMINISTRASI' OR 'PEKERJAAN' LIKE 'STAF AHLI' 
8. Tampilkan yang masa kerjanya diatas >5 tahun dan gajinya diatas 4000000
SELECT * FROM KARYAWAN WHERE MKERJA>5 AND GAJI>4000000
9. Tampilkan yang Namanya berhuruf depan S dan Gaji nya kurang <1000000
SELECT * FROM KARYAWAN WHERE NAMA LIKE 'S%' AND GAJI<1000000
10. Tampilkan yang gajinya diatas >1000000 dan Masa Kerjanya >4 th
SELECT * FROM KARYAWAN WHERE GAJI>1000000 AND MKERJA>4
11. Gantilah yang pekerjaannya KEAMANAN menjadi SATPAM
UPDATE KARYAWAN SET PEKERJAAN='SATPAM' WHERE PEKERJAAN='KEAMANAN'
12. Nama AHMAD ZAENUDIN seharusnya SLAMET ACHMAD perbaikilah.
UPDATE KARYAWAN SET NAMA='SLAMET ACHMAD' WHERE MKERJA='8' 
13. Karyawan yang bernama SANTOSO dan SURAJAYA mengundurkan diri,
hapuslah datanya.
DELETE FROM KARYAWAN WHERE NAMA='SANTOSO' AND NAMA='SARAJAYA'
14. Tampilkan data NAMA, JABATAN dan GAJI yang jabatannya STAF AHLI
SELECT NAMA, PEKERJAAN, GAJI FROM KARYAWAN WHERE PEKERJAAN='STAF AHLI'
15. Tampilkan data NAMA dan GAJI dimana gaji sudah naik 3%
SELECT NAMA, GAJI*3/100+GAJI AS GAJI
FROM KARYAWAN
16. Terjadi pergantian tahun, semua Masa Kerja bertambah 1 tahun dan semua GAJI
naik 10% perbaikilah datanya.
UPDATE KARYAWAN
SET MKERJA=MKERJA+1
UPDATE KARYAWAN
SET GAJI=GAJI*10/100+GAJI

SELECT * FROM KARYAWAN